fix: package.json err-code module missing.
Error: Cannot find module 'err-code'
Require stack:
- D:\code\web3\solscan\node_modules\promise-retry\index.js